name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - run: |
        set -x
        echo $PATH
        which clang
        which cc
        which gcc

        cc --version
        /Library/Developer/CommandLineTools/usr/bin/cc --version

        export PATH=/Library/Developer/CommandLineTools/usr/bin/:$PATH

        sudo xcode-select -switch /Applications/Xcode_12.2.app

        which clang
        which cc
        which gcc

        cc --version
        /Library/Developer/CommandLineTools/usr/bin/cc --version

        make universal_app CC=/Library/Developer/CommandLineTools/usr/bin/cc
