name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - run: |
        set -x
        echo $PATH
        which clang
        which cc
        which gcc

        ls -lR /Library/Developer/CommandLineTools || true
        ls -lR $HOME/Library/Developer/CommandLineTools || true

        cc --version

        sudo xcode-select -switch /Applications/Xcode_12.2.app

        which clang
        which cc
        which gcc

        cc --version

        make universal_app
